#cloud-config

# Enable cloud-init modules
cloud_config_modules:
  - runcmd
  - timezone
  - package-update-upgrade-install
  - resolv_conf

# Set TimeZone
timezone: America/Toronto

# Set DNS
manage_resolv_conf: true

resolv_conf:
  nameservers: ['192.168.2.213']

# Install packages
packages:
  - mlocate
  - vim
  - epel-release

# Update/Upgrade & Reboot if necessary
## package_update: true
## package_upgrade: true
## package_reboot_if_required: true

# Reset root password
runcmd:
 - echo "jandrew28" | passwd --stdin root
 - curl --insecure https://raw.githubusercontent.com/kevinwood75/salt-install/master/minion-install.sh | bash -
 - salt-call state.highstate > /tmp/highstate.log 

# Remove cloud-init
# runcmd:
#  - yum -y remove cloud-init
#  - updatedb

# Configure where output will go

output:
  all: ">> /var/log/cloud-init.log"

# vim:syntax=yaml
